# Makefile for offline CASACNP:
#
# module load compiler/gnu/8.1.0
# gfortran -v
# gcc version 8.1.0 (GCC)

# For profiling (use -pg instead of -g):
#PROG = ./casaclm_mimics_corpse_test
#PROG = ./casaclm_mimics-cn_corpse.p
PROG = ./casaclm_mimics-cn_corpse

#FC = ifort                    # compiler on both cherax and shine (-CB = check bounds)
#FFLAGS = -O0 -CB

#FC = f95 
FC = gfortran     
                
#FFLAGS = -g -C -fbacktrace -fbounds-check
#FFLAGS = -g -C -fbacktrace -fbounds-check -fdefault-real-8 -fdefault-double-8 -fcheck=all -Wall
#FFLAGS = -g -C -fbacktrace -fbounds-check -fdefault-real-8 -fdefault-double-8
# For profiling (use -pg instead of -g):
#FFLAGS = -pg -C -fbacktrace -fbounds-check -fdefault-real-8 -fdefault-double-8 -fcheck=all -Wall
#FFLAGS = -g -C -fbacktrace -fbounds-check -fdefault-real-8 -fdefault-double-8 -fcheck=all -Wall
# Turn off debugging option and compile with optimization at level 1 (~4x speedup)
FFLAGS = -O1 -C -fbacktrace -fbounds-check -fdefault-real-8 -fdefault-double-8 -fcheck=all -Wall

#LIB_NETCDF=	/usr/local/netcdf/lib 
#INCS=	/usr/local/include

# Updated the paths 8/6/2018
#LIB_NETCDF=	/usr/local/netcdf-c-4.6.1-f-4.4.4-gcc-g++-gfortran-4.8.5/lib	
#INCS=	/usr/local/netcdf-c-4.6.1-f-4.4.4-gcc-g++-gfortran-4.8.5/include

# Updated the paths (8/20/2018)
LIB_NETCDF=	/usr/local/netcdf-c-4.6.1-f-4.4.4-gcc-g++-gfortran-8.1.0/lib	
INCS=	/usr/local/netcdf-c-4.6.1-f-4.4.4-gcc-g++-gfortran-8.1.0/include

$(PROG): casaoffline_driver_clm_CN.o 
	$(FC) $(FFLAGS) -o $(PROG) casaoffline_driver_clm_CN.o casa_inout.o mimics_inout_CN.o \
	casa_cnp.o casa_nlim.o mimics_cycle_CN.o casa_vegsoil.o casa_variable.o mimics_variable_CN.o \
	corpse_variable.o corpse_soil_carbon.o corpse_inout.o corpse_cycle.o -L$(LIB_NETCDF) -lnetcdff -lm

casaoffline_driver_clm_CN.o: casaoffline_driver_clm_CN.f90 casa_vegsoil.o casa_cnp.o mimics_cycle_CN.o \
	casa_variable.o mimics_variable_CN.o corpse_variable.o casa_inout.o mimics_inout_CN.o corpse_inout.o corpse_cycle.o
	$(FC) $(FFLAGS) -c casaoffline_driver_clm_CN.f90 

casa_vegsoil.o: casa_vegsoil.f90 casa_variable.o
	$(FC) $(FFLAGS) -c casa_vegsoil.f90

casa_variable.o: casa_variable.f90 
	$(FC) $(FFLAGS) -c casa_variable.f90

casa_nlim.o: casa_nlim.f90 casa_vegsoil.o casa_variable.o
	$(FC) $(FFLAGS) -c casa_nlim.f90

mimics_variable_CN.o: mimics_variable_CN.f90 
	$(FC) $(FFLAGS) -c mimics_variable_CN.f90

casa_inout.o: casa_inout.f90 casa_vegsoil.o casa_variable.o casa_cnp.o mimics_cycle_CN.o mimics_inout_CN.o corpse_inout.o \
	corpse_cycle.o corpse_inout.o casa_nlim.o
	$(FC) $(FFLAGS) -c -I$(INCS) casa_inout.f90

mimics_inout_CN.o: mimics_inout_CN.f90 casa_variable.o mimics_variable_CN.o 
	$(FC) $(FFLAGS) -c -I$(INCS) mimics_inout_CN.f90

mimics_cycle_CN.o: mimics_cycle_CN.f90 casa_variable.o mimics_variable_CN.o 
	$(FC) $(FFLAGS) -c -I$(INCS) mimics_cycle_CN.f90

casa_cnp.o: casa_cnp.f90 casa_vegsoil.o casa_variable.o
	$(FC) $(FFLAGS) -c casa_cnp.f90

corpse_soil_carbon.o: corpse_soil_carbon.f90
	$(FC) $(FFLAGS) -c corpse_soil_carbon.f90

corpse_variable.o: corpse_variable.f90 corpse_soil_carbon.o
	$(FC) $(FFLAGS) -c corpse_variable.f90

corpse_inout.o: corpse_inout.f90 corpse_variable.o 
	$(FC) $(FFLAGS) -c -I$(INCS) corpse_inout.f90

corpse_cycle.o: corpse_cycle.f90 corpse_variable.o corpse_soil_carbon.o
	$(FC) $(FFLAGS) -c -I$(INCS) corpse_cycle.f90

clean:
	rm -f *.o $(PROG) *.mod
	ln -s $(NCMOD) ./netcdf.mod

